# Generated by Django 3.1.7 on 2021-03-30 01:14

import django.contrib.auth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(settings.AUTH_USER_MODEL.lower(), models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, default='en', max_length=8, verbose_name='language')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cover', models.ImageField(blank=True, default='', max_length=255, upload_to='lotus/category/cover/%y/%m', verbose_name='cover image')),
                ('original', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotus.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, default='en', max_length=8, verbose_name='language')),
                ('status', models.SmallIntegerField(choices=[(0, 'draft'), (10, 'available')], db_index=True, default=0, verbose_name='status')),
                ('publish_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='publication date')),
                ('publish_time', models.TimeField(default=django.utils.timezone.now, verbose_name='publication time')),
                ('publish_end', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='publication end')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update')),
                ('title', models.CharField(default='', max_length=150, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('lead', models.TextField(blank=True, verbose_name='lead')),
                ('introduction', models.TextField(blank=True, verbose_name='introduction')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('cover', models.ImageField(blank=True, default='', max_length=255, upload_to='lotus/article/cover/%y/%m', verbose_name='cover image')),
                ('image', models.ImageField(blank=True, default='', max_length=255, upload_to='lotus/article/image/%y/%m', verbose_name='main image')),
                ('authors', models.ManyToManyField(blank=True, related_name='articles', to='lotus.Author', verbose_name='authors')),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='lotus.Category', verbose_name='categories')),
                ('original', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotus.article')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['title'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('slug', 'language'), name='lotus_unique_cat_slug_lang'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('original', 'language'), name='lotus_unique_cat_original_lang'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('publish_date', 'slug', 'language'), name='lotus_unique_art_pub_slug_lang'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('original', 'language'), name='lotus_unique_art_original_lang'),
        ),
    ]
