# Generated by Django 4.2.6 on 2023-11-24 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lotus", "0002_add_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="modified",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modification date",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="modified",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modification date",
            ),
        ),
        migrations.AlterField(
            model_name="albumitem",
            name="modified",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modification date",
            ),
        ),
    ]
