# Generated by Django 4.2.16 on 2024-10-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotus", "0004_add_category_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_alt_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=125,
                verbose_name="cover alternative text",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=125,
                verbose_name="main alternative text",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="cover_alt_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=125,
                verbose_name="cover alternative text",
            ),
        ),
    ]
