# Generated by Django 5.2.3 on 2025-06-24 00:30

from django.db import migrations, models

from ..choices import (
    get_article_template_choices, get_article_template_default,
    get_category_template_choices, get_category_template_default,
)

class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0005_add_article_category_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='template',
            field=models.CharField(choices=get_article_template_choices(), default=get_article_template_default(), max_length=150, verbose_name='template'),
        ),
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.CharField(choices=get_category_template_choices(), default=get_category_template_default(), max_length=150, verbose_name='template'),
        ),
    ]
